# Версия docker-compose
version: '3'

# Список наших сервисов (контейнеров)
services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
    - ./hosts:/etc/nginx/conf.d
    - ./www:/var/www
    - ./logs:/var/log/nginx
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
    restart: unless-stopped
    # монтируем директорию с проектами
    volumes:
    - ./www:/var/www

  memcached:
    image: 'bitnami/memcached:latest'
    ports:
      - 11111:11211
    volumes:
      - ./memcached/memcached.conf:/etc/memcached.conf

  mariadb:
    image: mariadb
    restart: unless-stopped
    ports:
    - 3306:3306
    volumes:
    - ./mysql:/var/lib/mysql
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: anilibria
      MYSQL_PASSWORD: anilibria
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: anilibria
      PMA_HOST: mariadb
      PMA_PORT: 3306

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
    - 8180:8080
    depends_on:
      - mariadb
  xbt_tracker:
    image: kauden/xbt_tracker:latest
#    volumes:
#      - ./images/xbt_tracker/xbt_tracker.conf:/opt/xbt_tracker/xbt_tracker.conf
    depends_on:
    - mariadb

  sphinx:
    build: ./sphinx
    restart: unless-stopped
    depends_on:
    - mariadb
#    volumes:
#    - ./sphinx/sphinx.conf:/etc/sphinxsearch/sphinx.conf
#    - ./sphinxsearch:/var/lib/sphinxsearch/data