# Версия docker-compose
version: '3'

# Список наших сервисов (контейнеров)
services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    ports:
    - "80:80"
    - "443:443"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
    - ./hosts:/etc/nginx/conf.d
    - ./www:/var/www
    - ./logs:/var/log/nginx
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
    # монтируем директорию с проектами
    volumes:
    - ./www:/var/www

  memcached:
    image: 'bitnami/memcached:latest'
    ports:
      - 11111:11211
    volumes:
      - ./memcached/memcached.conf:/etc/memcached.conf

  mariadb:
    image: mariadb
    restart: always
    ports:
    - 3306:3306
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
      PMA_HOST: mariadb
      PMA_PORT: 3306

  adminer:
    image: adminer
    restart: always
    ports:
    - 8180:8080
    depends_on:
      - mariadb
  xbt_tracker:
    build: ./images/xbt_tracker